import type { ProductImageStatus } from "../product-media/product-media-normalizer";

export type ProductPassportStatus = "DRAFT" | "ACTIVE" | "NEEDS_REVIEW" | "ARCHIVED";

export type ProductPassportInput = {
  sellerId: string;
  sku?: string | null;
  asin?: string | null;
  productName: string;
  brand?: string | null;
  category?: string | null;
  subCategory?: string | null;
  productType?: string | null;
  sellingPrice?: number | null;
  targetCustomer?: string | null;
  useCase?: string | null;
  material?: string | null;
  color?: string | null;
  dimensions?: string | null;
  weight?: string | null;
  packageContents?: string | null;
  keyFeatures?: unknown[];
  customerObjections?: unknown[];
  competitorAsins?: unknown[];
  imageUrls?: unknown[];
  supplierName?: string | null;
  supplierCost?: number | null;
  packagingNotes?: string | null;
  brandPositioning?: string | null;
  seoKeywords?: unknown[];
  complianceNotes?: string | null;
  internalNotes?: string | null;
  status?: ProductPassportStatus;
};

export type ProductPassportUpdateInput = Partial<Omit<ProductPassportInput, "sellerId">> & {
  sellerId?: string;
};

export type ProductPassportRow = {
  id: string;
  seller_id: string;
  sku: string | null;
  asin: string | null;
  product_name: string;
  brand: string | null;
  category: string | null;
  sub_category: string | null;
  product_type: string | null;
  selling_price: number | string | null;
  target_customer: string | null;
  use_case: string | null;
  material: string | null;
  color: string | null;
  dimensions: string | null;
  weight: string | null;
  package_contents: string | null;
  key_features: unknown[] | null;
  customer_objections: unknown[] | null;
  competitor_asins: unknown[] | null;
  image_urls: unknown[] | null;
  supplier_name: string | null;
  supplier_cost: number | string | null;
  packaging_notes: string | null;
  brand_positioning: string | null;
  seo_keywords: unknown[] | null;
  compliance_notes: string | null;
  internal_notes: string | null;
  status: ProductPassportStatus;
  created_at: string;
  updated_at: string;
};

export type SafeProductPassportRow = {
  id: string;
  sellerId: string;
  sku: string | null;
  asin: string | null;
  productName: string;
  brand: string | null;
  category: string | null;
  subCategory: string | null;
  productType: string | null;
  sellingPrice: number | null;
  targetCustomer: string | null;
  useCase: string | null;
  material: string | null;
  color: string | null;
  dimensions: string | null;
  weight: string | null;
  packageContents: string | null;
  keyFeatures: unknown[];
  customerObjections: unknown[];
  competitorAsins: unknown[];
  imageUrls: unknown[];
  mainImageUrl: string | null;
  imageUrl: string | null;
  amazonImageUrl: string | null;
  imageSource: string | null;
  lastImageSyncAt: string | null;
  images: string[];
  imageStatus: ProductImageStatus | string;
  supplierName: string | null;
  supplierCost: number | null;
  packagingNotes: string | null;
  brandPositioning: string | null;
  seoKeywords: unknown[];
  complianceNotes: string | null;
  internalNotes: string | null;
  status: ProductPassportStatus;
  createdAt: string;
  updatedAt: string;
};
