export type ProductProfitStatus = "PASS" | "RISK" | "FAIL" | "UNKNOWN" | "NEEDS_COST_DATA" | "NEEDS_INPUT" | "BLOCKED";
export type CostCompletionStatus = "MISSING_COST_DATA" | "INCOMPLETE" | "COMPLETE" | "BLOCKED";

export type ProductEconomicsInput = {
  sellerId: string;
  marketplaceId?: string | null;
  asin?: string | null;
  sku?: string | null;
  productName?: string | null;
  subCategory?: string | null;
  subcategoryOverride?: string | null;
  fulfillmentType?: string | null;
  productType?: string | null;
  shippingRegion?: string | null;
  categoryException?: boolean | null;
  weightKg?: number | null;
  volumeCuFt?: number | null;
  hiddenOtherFee?: number;
  productGstRatePercent?: number;
  amazonFeeGstRatePercent?: number;
  minimumApprovedProfit?: number;
  profitFlexEnabled?: boolean;
  sellingPrice: number;
  productCost?: number;
  buyingCost?: number;
  landedCost: number;
  packagingCost: number;
  amazonFeeEstimate: number;
  shippingFeeEstimate: number;
  taxEstimate: number;
  returnRatePercent: number;
  returnCostPerReturn: number;
  returnReservePerUnit?: number;
  influencerCostAllocationPerUnit: number;
  socialMarketingCostPerUnit: number;
  couponDiscountEstimate: number;
  otherFees?: number;
  otherCostPerUnit: number;
  targetProfit?: number;
  notes?: string | null;
};

export type ProfitBand = {
  bandLabel: string;
  minProfit: number;
  maxProfit: number;
  targetAcos: number | null;
  maxAllowableAdSpend: number | null;
  riskLevel: "LOW" | "MEDIUM" | "HIGH" | "VERY_HIGH";
  approvalRequired: boolean;
  approvalTier: "PROFIT_BAND_APPROVAL" | "HIGH_RISK_APPROVAL" | "FOUNDER_OVERRIDE_REQUIRED";
  warning: string | null;
};

export type ProfitBandApproval = {
  approvalType: "PROFIT_BAND_APPROVAL";
  sku: string | null;
  currentRequiredProfit: number;
  requestedProfitBand: ProfitBand | null;
  riskLevel: ProfitBand["riskLevel"] | null;
  reason: string;
  expiresInDays: 7;
};

export type ProductEconomicsCalculation = {
  targetProfit: number;
  targetProfitRule: string;
  returnReservePerUnit: number;
  nonAdCost: number;
  maxAllowableAdSpend: number | null;
  breakEvenAcos: number | null;
  targetAcos: number | null;
  profitStatus: ProductProfitStatus;
  profitDataStatus: "AVAILABLE" | "MISSING_COST_DATA" | "INCOMPLETE";
  referralFeeSource: "REFERRAL_FEE_TABLE" | "MISSING_SUBCATEGORY" | "NO_MATCH";
  referralFeePercent: number | null;
  referralFee: number;
  closingFee: number;
  shippingFee: number;
  pickAndPackFee: number;
  storageFee: number;
  manualOtherFees: number;
  otherFees: number;
  totalAmazonFees: number;
  gstOnAmazonFees: number;
  grossProfit: number | null;
  netProfit: number | null;
  profitMarginPercent: number | null;
  productGstRatePercent: number;
  amazonFeeGstRatePercent: number;
  netRevenueBeforeGst: number | null;
  outputGstOnSale: number | null;
  returnCostProvision: number;
  hiddenOtherFee: number;
  netProfitBeforeAds: number | null;
  minimumApprovedProfit: number;
  profitFlexEnabled: boolean;
  profitBands: ProfitBand[];
  recommendedProfitBand: ProfitBand | null;
  recommendedProfitBandReason: string;
  approval: ProfitBandApproval | null;
  feeRulesVersion: string;
  reason: string;
};

export type ProductEconomicsExplanation = {
  profitStatus: ProductProfitStatus;
  profitDataStatus: "AVAILABLE" | "MISSING_COST_DATA" | "INCOMPLETE";
  targetProfit: number;
  nonAdCost: number;
  maxAllowableAdSpend: number | null;
  breakEvenAcos: number | null;
  targetAcos: number | null;
  reason: string;
};

export type ProductEconomicsRow = {
  id: string;
  seller_id: string;
  marketplace_id: string | null;
  asin: string | null;
  sku: string | null;
  product_name: string | null;
  selling_price: number | string;
  landed_cost: number | string | null;
  packaging_cost: number | string | null;
  amazon_fee_estimate: number | string | null;
  shipping_fee_estimate: number | string | null;
  tax_estimate: number | string | null;
  return_rate_percent: number | string | null;
  return_cost_per_return: number | string | null;
  return_reserve_per_unit: number | string | null;
  influencer_cost_allocation_per_unit: number | string | null;
  social_marketing_cost_per_unit: number | string | null;
  coupon_discount_estimate: number | string | null;
  other_cost_per_unit: number | string | null;
  target_profit: number | string;
  target_profit_rule: string | null;
  non_ad_cost: number | string | null;
  max_allowable_ad_spend: number | string | null;
  break_even_acos: number | string | null;
  target_acos: number | string | null;
  profit_status: ProductProfitStatus;
  notes: string | null;
  created_at: string | null;
  updated_at: string | null;
};

export type SafeProductEconomicsRow = {
  id: string;
  sellerId: string;
  marketplaceId: string | null;
  asin: string | null;
  sku: string | null;
  productName: string | null;
  sellingPrice: number;
  buyingCost: number;
  landedCost: number;
  packagingCost: number;
  shippingCost: number;
  referralFee: number;
  closingFee: number;
  shippingFee: number;
  pickAndPackFee: number;
  storageFee: number;
  manualOtherFees: number;
  otherFees: number;
  totalAmazonFees: number;
  gstOnAmazonFees: number;
  grossProfit: number | null;
  netProfit: number | null;
  profitMarginPercent: number | null;
  productGstRatePercent: number;
  amazonFeeGstRatePercent: number;
  netRevenueBeforeGst: number | null;
  outputGstOnSale: number | null;
  returnCostProvision: number;
  hiddenOtherFee: number;
  netProfitBeforeAds: number | null;
  minimumApprovedProfit: number;
  profitFlexEnabled: boolean;
  profitBands: ProfitBand[];
  recommendedProfitBand: ProfitBand | null;
  recommendedProfitBandReason: string;
  approval: ProfitBandApproval | null;
  referralFeePercent: number | null;
  referralFeeSource: "REFERRAL_FEE_TABLE" | "MISSING_SUBCATEGORY" | "NO_MATCH";
  feeRulesVersion: string;
  amazonFeeEstimate: number;
  shippingFeeEstimate: number;
  taxEstimate: number;
  returnRatePercent: number;
  returnCostPerReturn: number;
  returnReservePerUnit: number;
  influencerCostAllocationPerUnit: number;
  socialMarketingCostPerUnit: number;
  couponDiscountEstimate: number;
  otherCostPerUnit: number;
  requiredProfit: number;
  targetProfit: number;
  targetProfitRule: string | null;
  nonAdCost: number;
  maxAllowableAdSpend: number | null;
  breakEvenAcos: number | null;
  targetAcos: number | null;
  profitStatus: ProductProfitStatus;
  profitDataStatus: "AVAILABLE" | "MISSING_COST_DATA" | "INCOMPLETE";
  reason: string;
  notes: string | null;
  createdAt: string | null;
  updatedAt: string | null;
};

export type CostCompletionQueueRow = {
  sku: string | null;
  asin: string | null;
  productName: string | null;
  subcategory: string | null;
  subCategory: string | null;
  subcategorySource: "PRODUCT_PASSPORT" | "AMAZON_LISTING" | "ECONOMICS_NOTES" | "MISSING";
  sellingPrice: number | null;
  costStatus: CostCompletionStatus;
  profitStatus: ProductProfitStatus | null;
  profitDataStatus: SafeProductEconomicsRow["profitDataStatus"] | null;
  missingFields: string[];
  targetAcos: number | null;
  breakEvenAcos: number | null;
  existingEconomics: SafeProductEconomicsRow | null;
  nextActionLabel: string;
};
