export type TodayCommandSystemStatus = {
  actionLedgerReady: boolean;
  approvalCenterReady: boolean;
  engineRegistryReady: boolean;
  engineRouterReady: boolean;
  dailyOrchestratorReady: boolean;
  productPassportReady: boolean;
  productEconomicsReady: boolean;
  learningLoopReady: boolean;
  executionGatewayReady: boolean;
  safetyControlReady: boolean;
  alertCenterReady: boolean;
  experimentsReady: boolean;
  dataFreshnessReady: boolean;
  aiGatewayReady: boolean;
  productionHealthReady: boolean;
  activityLogsReady: boolean;
  rollbackReady: boolean;
  approvalExecutionReady: boolean;
  maintenanceReady: boolean;
  qaSmokeReady: boolean;
  liveExecutionReady: boolean;
  launchGateReady: boolean;
  launchChecklistReady: boolean;
  schedulerControlReady: boolean;
  notificationOutboxReady: boolean;
  securityGuardrailsReady: boolean;
};

export type TodayCommandCounts = {
  pendingApprovals: number;
  approvedActions: number;
  completedActions: number;
  rejectedActions: number;
  totalEngines: number;
  enabledEngines: number;
  last24hEngineRuns: number;
  last24hActionsCreated: number;
  totalLearningEvents: number;
  enginesTracked: number;
  executionAttempts: number;
  shadowExecutions: number;
  listingDrafts: number;
  creativeRecommendations: number;
  openAlerts: number;
  highAlerts: number;
  runningExperiments: number;
  completedExperiments: number;
  staleDataSources: number;
  aiCostToday: number;
  aiCostMonth: number;
  activityEventsToday: number;
  rollbackSnapshots: number;
  executableApprovedActions: number;
  latestMaintenanceStatus: string | null;
  latestQaStatus: string | null;
  qaPassCount: number;
  qaWarnCount: number;
  qaFailCount: number;
  schedulerJobs: number;
  notificationQueued: number;
  liveExecutionRuns: number;
  securityBlockedEvents: number;
};

export type TodayCommandSummary = {
  ok: true;
  sellerId: string;
  mode: "SHADOW";
  systemStatus: TodayCommandSystemStatus;
  counts: TodayCommandCounts;
  topRisks: unknown[];
  todayPriorities: unknown[];
  nextBestActions: unknown[];
  launchGateStatus: string | null;
  launchChecklistStatus: string | null;
  schedulerJobs: number;
  notificationQueued: number;
  liveExecutionRuns: number;
  latestDryRunStatus: string | null;
  liveEligible: boolean;
  ppcLiveEligible: boolean;
  listingLiveEligible: boolean;
  securityBlockedEvents: number;
  launchNextSteps: unknown[];
  safety: {
    shadowMode: boolean;
    externalExecution: false;
    liveExecutionEnabled: boolean;
    aiCallsEnabled: boolean;
  };
  warnings: string[];
};
